spring:
  datasource:
      url: jdbc:mysql://localhost:3306/yan1?characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #mail
  mail:  
    host: smtp.qq.com  
    username: 1479676948@qq.com
    password: duytlpvbnsqigfjd
    properties:  
      mail:  
        smtp:  
          auth: true  
          starttls:  
            enable: true  
            required: true  